### ISSUE TITLE
Minor compatibility with Blur mod

### ISSUE THREAD

**Issue by Sephoix** [DenWav/ExtendedHotbar#10]
Running Fabric 1.20.1.
Noticed that the blur mod flickers whenever swapping items/hotbar rows. Looked at the logs and the logging feature Blur provides and discovered this mod shares the same class as the main inventory: net.minecraft.class_490

https://github.com/DenWav/ExtendedHotbar/assets/85546419/570e7836-5533-4cad-9204-9e360d193f21

**Comment by DenWav** [comment]
Thanks, I'll look into it. Leaving a link to the mod for my own reference later: https://modrinth.com/mod/blur-fabric

**Comment by DenWav** [comment]
I assume what's going on here is related to how this mod works. To do the swap, the inventory is "opened", the items are swapped, then the inventory is "closed" - this all happens within a single tick so nothing ever appears for the player.

I assume while the inventory is briefly virtually "opened", the blur effect still occurs. I have a couple ideas of how I could mitigate this, but right now I'm not sure what the best option is. I'll find out soon enough.
