### ISSUE TITLE
(Suggestion) Backport fluent mode to 1.20.1

### ISSUE THREAD

**Issue by IZeeXeS** [DenWav/ExtendedHotbar#13]
because many mods still not updated / will never update to 1.20.4 / wait to 1.21

**Comment by DenWav** [comment]
Yeah it wouldn't hurt.

**Comment by TophC7** [comment]
I'd love to see this too, awesome mod <3

**Comment by Trold10** [comment]
Yeah! Please do this! Sorry to stress but I get kicked when not using this so would be really nice to see it :)

**Comment by DenWav** [comment]
Yeah sorry I just need to find some time this weekend to knock this out. Will add it to my to-do list.

**Comment by DenWav** [comment]
Alright I've nearly got this done, will push a release soon. Considering making fluent mode the default since I think it's a lot nicer to use.

**Comment by DenWav** [comment]
Alright, fluent mode for 1.20.1 is released. https://modrinth.com/mod/extended-hotbar/version/haTgOnRJ
