### ISSUE TITLE
Item #2 from hotbar gets "removed" when swapping bars

### ISSUE THREAD

**Issue by SXRWahrheit** [DenWav/ExtendedHotbar#7]
When pressing the hotbar switch key (I have it bound to R), my bow in slot #2 will be in my hand when I open my inventory, and disappear until then. Obviously not ideal for combat. :)

**Comment by DemonWav** [comment]
Does the off hand effect it at all? I don't think I handle it, which may be causing the problem.

**Comment by DemonWav** [comment]
Okay after forgetting that this project existed entirely I came back and updated it for 1.16.[2,3,4] and switched to Fabric, and I tried to reproduce this but can't seem to. Maybe the issue isn't present anymore on 1.16?
