### ISSUE TITLE
Hotbar overlaps Action Bar.

### ISSUE THREAD

**Issue by PINPAL** [DenWav/ExtendedHotbar#9]
**Description**
The hotbar overlaps the action bar. See screenshot for further details.

![Screenshot 2023-07-02 141934](https://github.com/DenWav/ExtendedHotbar/assets/18197217/da6194e8-cc07-4ab3-8fd2-c3162d9ef840)

**Comment by DenWav** [comment]
Thanks for pointing this out. Will fix when I get the chance, soon.
